### ISSUE TITLE
Artwork license?

### ISSUE THREAD

**Issue by jess-sch** [systemd/brand.systemd.io#1]
I think clarifying the license would be a pretty good idea. Right now, the website doesn't give any clue about that. Would be useful just in case someone asks themselves whether they can print it on a shirt or something.

**Comment by xnox** [comment]
And i think the assets need to be registered as trademarks in the US as well, which SPI can do for systemd.

**Comment by SJrX** [comment]
Yes in particular I maintain a plugin that provides some assistance in editing unit files. I think it would probably be good if I could re-use the logo, instead of using my own which looks like nothing.

**Comment by poettering** [comment]
It's now licensed under CC-BY-SA. See LICENSE file
