### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [systemd/brand.systemd.io#4]
Please do not ignore this property of useragent
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by keszybz** [comment]
@vitaly-zdanevich this is way above our understanding of html and css. If you know what to do, please submit a pull request. We'll be very grateful.

**Comment by bnf** [comment]
I will provide a PR to include the CSS/SVG changes for dark-mode – as merged in https://github.com/systemd/systemd/pull/23417 – in this repository as well.
